#!/usr/bin/env bash

TEMPDIR=50-2-25.temp.$$
mkdir $TEMPDIR

for file in "$@"; do
    if [[ $(( $(ffprobe -v error -select_streams v:0 -show_entries stream=avg_frame_rate -of default=noprint_wrappers=1:nokey=1 "$file") )) -ne 50 ]]; then
        echo "$file isn't 50fps, ignoring"
    else
        echo "$file is 50fps"
        cp "$file" $TEMPDIR/
    fi
done

(
    cd $TEMPDIR

    FILES=$( (ls "$@" 2>/dev/null) |wc -l)
    if [[ $FILES -ne 0 ]]; then
        echo Converting $FILES files to 25fps
        USECPUS=1
        AVAILABLECPUS=$(( $(nproc) - 1 ))
        if [[ $AVAILABLECPUS -eq 0 ]]; then
            AVAILABLECPUS=1
        elif [[ $AVAILABLECPUS -gt $FILES ]]; then
            USECPUS=$(( $AVAILABLECPUS / $FILES ))
        fi
        if [[ $USECPUS -eq 0 ]]; then
            USECPUS=1
        fi
        echo ... found $AVAILABLECPUS CPUs, running at most that many jobs in parallel    
        echo ... using $USECPUS CPUs per file

        rotator &
        (ls "$@" 2>/dev/null) | parallel -j $AVAILABLECPUS ffmpeg -y -hide_banner -loglevel error -cpucount $USECPUS -i {} -filter:v fps=25 ../{}
        kill %1
        sleep 1 # wait for kill to work
        echo Done
    fi
)

rm -rf $TEMPDIR
