#!/usr/bin/env bash

if [ "$1" = "--onecpu" ]; then
    shift
    ONECPU=1
elif [ "$1" = "--do_one" ]; then
    TEMPDIR="$2"
    USECPUS="$3"
    FILE="$4"
    ffmpeg -y -hide_banner -loglevel error -threads $USECPUS -i "$FILE" -filter:v fps=25 "$TEMPDIR/$FILE" && \
        mv "$TEMPDIR/$FILE" "$FILE"
    exit
fi

TO_PROCESS=()
TEMPDIR=50-2-25.temp.$$
mkdir $TEMPDIR

echo Checking files
for file in "$@"; do
    if [[ $( fps "$file" ) -ne 50 ]]; then
        echo "... $file isn't 50fps, ignoring"
    else
        echo "... $file is 50fps"
        TO_PROCESS+=("$file")
    fi
done

(
    FILES=${#TO_PROCESS[@]}
    if [[ $FILES -ne 0 ]]; then
        echo Converting $FILES files to 25fps
        USECPUS=1
        AVAILABLECPUS=$(( $(nproc) / 2 ))
        if [[ $AVAILABLECPUS -eq 0 ]] || [[ $ONECPU -eq 1 ]]; then
            AVAILABLECPUS=1
        elif [[ $AVAILABLECPUS -gt $FILES ]]; then
            USECPUS=$(( $AVAILABLECPUS / $FILES ))
        fi
        if [[ $USECPUS -eq 0 ]]; then
            USECPUS=1
        fi
        echo ... found $AVAILABLECPUS CPUs, running at most that many jobs in parallel
        echo ... using $USECPUS CPUs per file

        rotator &
        (
            for i in ${!TO_PROCESS[@]}; do
                echo ${TO_PROCESS[$i]}
            done
        ) | parallel -j $AVAILABLECPUS "$0" --do_one "$TEMPDIR" $USECPUS "{}"
        kill %1
        sleep 1 # wait for kill to work
        echo Done
    fi
)

rm -rf $TEMPDIR
