#!/usr/bin/env bash

TO_PROCESS=()
TEMPDIR=50-2-25.temp.$$
mkdir $TEMPDIR

echo Checking files
for file in "$@"; do
    if [[ $( ffverify -q "$file" && fps "$file" ) -ne 50 ]]; then
        echo "... $file isn't well-formed 50fps, ignoring"
    else
        echo "... $file is 50fps"
        TO_PROCESS+=("$file")
    fi
done

rotator &

for i in ${!TO_PROCESS[@]}; do
    FILE=${TO_PROCESS[$i]}
    TEMP_FILE="$TEMPDIR/$(basename "$FILE")"
    nice -n 19 ffmpeg -y -hide_banner -loglevel error -threads 1 -i "$FILE" -scodec copy -filter:v fps=25 "$TEMP_FILE"
    touch -r "$FILE" "$TEMP_FILE" && \
    mv "$TEMP_FILE" "$FILE"
done

kill %1
sleep 1 # wait for kill to work

rm -rf $TEMPDIR
