#!/usr/bin/env bash

eval "$(cat $HOME/bin/lib/stdbashlib)"

for file in "$@"; do
    (
        SECONDS=$(calc "int($(ffprobe -v error -select_streams a:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 "$file"))")

        echo -n $(seconds-to-hms "%dh %dm %ds" $SECONDS) && (
            if [ $# -ne 1 ]; then
                echo -n : $file
            fi
        ) &&
        echo
    ) || echo 0
done
