#!/usr/bin/env bash

for file in "$@"; do
    (
        DURATION="$(ffprobe -i "$file" -show_entries format=duration -v quiet -of csv="p=0" -sexagesimal | sed 's/\.[[:digit:]]*//')"

        echo -n $DURATION && (
            if [ $# -ne 1 ]; then
                echo -n : $file
            fi
        ) &&
        echo
    ) || echo 0
done
