#!/usr/bin/env bash

for file in "$@"; do
    (
        if [ $# -ne 1 ]; then
            echo "$file"
        fi

        eval "$(
            (echo FPS=\""$(fps "$file")"\")&
            (echo FFRES=\""$(ffres "$file")"\")&
            (echo FFDURATION=\""$(ffduration "$file")"\")&
            (echo SIZE=\""$(wc -c < "$file"|sed 's/ //g')"\")&
            wait
        )"
        echo "  fps:        $FPS"
        echo "  resolution: $FFRES"
        echo "  duration:   $FFDURATION"
        echo "  size:       $SIZE"
    )
done
