#!/usr/bin/env bash

CPULIMIT=500

if [ "$1" == "--cpulimit" ]; then
    CPULIMIT=$2
    shift
    shift
fi

NEWRES=$1
shift

TEMPDIR=ffsetres.temp.$$
mkdir $TEMPDIR

rotator &

for FILE in "$@"; do
    TEMP_FILE="$TEMPDIR/$(basename "$FILE")"
    cpulimit -l $CPULIMIT ffmpeg -i "$FILE" -s $NEWRES -c:a copy -c:s copy -loglevel error "$TEMP_FILE" || exit 1
    touch -r "$FILE" "$TEMP_FILE" && \
    mv "$TEMP_FILE" "$FILE"
done

kill %1
sleep 1 # wait for kill to work

rm -rf $TEMPDIR
