#!/usr/bin/env bash

eval "$(cat $HOME/bin/lib/stdbashlib)"

OUTPUT=/dev/stdout
if [ "$1" == "-q" ]; then
    OUTPUT=/dev/null
    shift
fi

(
    for i in "$@"; do
        printf "$i ... "
        (
            ffmpeg -v error -i "$i" -map 0:1 -f null - 2>/dev/null ||
            ffmpeg -v error -i "$i" -map 0:0 -f null - 2>/dev/null
        )

        err=$?
        if [[ $err == 255 ]]; then # ffmpeg died on signal, eg C-c
            printf "\n"
            exit 1
        elif [[ $err != 0 ]]; then
            red_text not ok
            exit 1
        else
            green_text ok
        fi
    done
) > $OUTPUT

exit $?
