#!/usr/bin/env bash

red='\e[1;31m'   # bold red
yellow='\e[0;33m'
green='\e[1;32m'
blue='\e[1;34m'
NC='\e[0m'       # no colour

OUTPUT=/dev/stdout
if [ "$1" == "-q" ]; then
    OUTPUT=/dev/null
    shift
fi

(
    for i in "$@"; do
        printf "$i ... "
        (
            ffmpeg -v error -i "$i" -map 0:1 -f null - 2>/dev/null ||
            ffmpeg -v error -i "$i" -map 0:0 -f null - 2>/dev/null
        )

        err=$?
        if [[ $err == 255 ]]; then # ffmpeg died on signal, eg C-c
            printf "\n"
            exit 1
        elif [[ $err != 0 ]]; then
            printf "${red}not ok${NC}\n"
            exit 1
        else
           printf "${green}ok${NC}\n"
        fi
    done
) > $OUTPUT

exit $?
