#!/usr/bin/env bash

for file in "$@"; do
    (
        echo -n $(ffmpeg -i "$file" 2>&1 | sed -n "s/.*, \(.*\) fp.*/\1/p") && (
            if [ $# -ne 1 ]; then
                echo -n : $file
            fi
        ) &&
        echo
    ) || echo 0
done
