#!/usr/bin/env bash

for file in "$@"; do
    (
        ffverify -q "$file" &&
        echo $(( $(ffprobe -v error -select_streams v:0 -show_entries stream=avg_frame_rate -of default=noprint_wrappers=1:nokey=1 "$file") ))
    ) || echo 0
done
