#!/usr/bin/env bash

export PATH=$PATH:/usr/local/bin

echo Recent PRs
echo
gh search prs --owner DrHyde    --state open --json createdAt,url --jq '(.[]|select(now - (.createdAt|fromdateiso8601) < 3600*24*60)).url'
gh search prs --owner rsnapshot --state open --json createdAt,url --jq '(.[]|select(now - (.createdAt|fromdateiso8601) < 3600*24*60)).url'

echo
echo Recent issues
echo
gh search issues --owner DrHyde    --state open --json createdAt,url --jq '(.[]|select(now - (.createdAt|fromdateiso8601) < 3600*24*60)).url'
gh search issues --owner rsnapshot --state open --json createdAt,url --jq '(.[]|select(now - (.createdAt|fromdateiso8601) < 3600*24*60)).url'

