#!/usr/bin/env bash

export PATH=$PATH:/usr/local/bin

echo Recent PRs
echo
for owner in DrHyde rsnapshot DBM-Deep; do
    gh search prs --owner $owner --state open --json createdAt,url --jq '(.[]|select(now - (.createdAt|fromdateiso8601) < 3600*24*60)).url'
done

echo
echo Recent issues
echo
for owner in DrHyde rsnapshot DBM-Deep; do
    gh search issues --owner $owner --state open --json createdAt,url --jq '(.[]|select(now - (.createdAt|fromdateiso8601) < 3600*24*60)).url'
done
