#!/bin/bash

set -euo pipefail

function main {
    MYDIR="$( cd "$(dirname "$0")"; pwd -P)"
    export PATH=$(
        echo $PATH | sed -E "
            s@$MYDIR@@g
            s/::/:/g
            s/^:+//
            s/:+\$//
        "
    )

    if [ "$#" -ge 2 ] && [ "$1" == "commit" ]; then
        for i in "$@"; do
            if [ "$i" == "-a" ] || [ "$i" == "--all" ]; then
                echo NO\! SHAN\'T\! $i is BAD\!
                exit 1;
            fi
        done
    fi
    exec git "$@"
}

main "$@"

