#!/usr/bin/env bash

eval "$(cat "$HOME/bin/lib/stdbashlib")"

this_scripts_dir="$(script_dir)"

remove_from_path "$this_scripts_dir"

real_killall="$(which killall 2>/dev/null)"

if [[ "$real_killall" != "" ]] && [[ $OSTYPE != solaris* ]]; then
    killall "$@"
else
    for pname in "$@"; do
        kill $(pgrep -U "$USER" "$pname")
    done
fi
