#!/usr/bin/env bash

for file in "$@"; do
    (
        file "$file"|grep "Matroska data" && \
        ffverify -q "$file"  && \
        ffmpeg -v error -i "$file" -codec copy "$file.mp4" && \
        touch -r "$file" "$file.mp4" && \
        rm "$file" \
    ) \
    || echo "... $file doesn't look like an mkv"
done
