#!/usr/bin/env bash

main () (
    VERB="$1"
    shift

    if [ "$VERB" == "list" ]; then
        list "$@"
    elif [ "$VERB" == "start" ]; then
        start "$@"
    elif [ "$VERB" == "stop" ]; then
        stop "$@"
    elif [ "$VERB" == "bounce" ]; then
        bounce "$@"
    else
        echo utm list\|start\|stop\|bounce
    fi
)

bounce () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( list up ); do
            bounce "$candidate"
        done
    elif [ -z "$MACHINE" ]; then
        echo utm bounce all\|\{list of machines\}
    else
        for candidate in "$MACHINE" "$@"; do
            if grep ^$candidate\$ <( list up ) >/dev/null 2>/dev/null ; then
                stop "$candidate"
                while grep "^$candidate$" <( list started ) >/dev/null 2>&1; do
                    sleep 5
                    echo ... waiting
                done
                sleep 5
                start "$candidate"
            else
                echo What\'s $candidate?
            fi
        done
    fi
)

stop () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( list up ); do
            stop "$candidate"
        done
    elif [ -z "$MACHINE" ]; then
        echo utm stop all\|\{list of machines\}
    else
        for candidate in "$MACHINE" "$@"; do
            if grep ^$candidate\$ <( list up ) >/dev/null 2>/dev/null ; then
                echo stopping $candidate
                utmctl stop "$candidate" --request >/dev/null 2>/dev/null
                sleep 5
            else
                echo What\'s $candidate?
            fi
        done
    fi
)

start () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( list stopped ); do
            start "$candidate"
        done
    elif [ -z "$MACHINE" ]; then
        echo utm start all\|\{list of machines\}
    else
        for candidate in "$MACHINE" "$@"; do
            if grep ^$candidate\$ <( list stopped ) >/dev/null 2>/dev/null ; then
                echo starting $candidate
                utmctl start $candidate >/dev/null 2>/dev/null
                while ! ping -c1 "$candidate" >/dev/null 2>&1; do
                    echo ... waiting
                    sleep 5
                done
            else
                echo What\'s $candidate?
            fi
        done
    fi
)

list_complete() (
    utmctl list |grep -v UUID
)

listall () (
    list_complete |awk '{print $3}'
)

liststarted () (
    list_complete |awk '$2 ~ /started/ { print $3; next }'
)

listup () (
    for candidate in $( liststarted ); do
        ping -c1 $candidate >/dev/null 2>/dev/null && echo $candidate
    done
)

list () (
    TYPE="$1"
    shift
    if [ "$TYPE" == "started" ]; then
        liststarted
    elif [ "$TYPE" == "all" ]; then
        listall
    elif [ "$TYPE" == "up" ]; then
        listup
    elif [ "$TYPE" == "stopped" ]; then
        grep -v -f <( liststarted ) <( listall )
    else
        echo utm list all\|started\|up\|stopped
    fi
)

main "$@"
