#!/usr/bin/env bash

eval "$(cat $HOME/bin/lib/stdbashlib)"

main () (
    ps aux|grep UTM.app/Contents/MacOS/UTM > /dev/null 2>&1 || (
        echo Need to start UTM
        open -a UTM
        sleep 5
    )

    VERB="$1"
    shift

    if [ "$VERB" == "list" ]; then
        list "$@"
    elif [ "$VERB" == "start" ]; then
        start "$@"
    elif [ "$VERB" == "stop" ]; then
        stop "$@"
    elif [ "$VERB" == "status" ]; then
        status "$@"
    elif [ "$VERB" == "backup" ]; then
        backup "$@"
    elif [ "$VERB" == "compress" ]; then
        compress "$@"
    elif [ "$VERB" == "bounce" ]; then
        bounce "$@"
    else
        echo utm list\|start\|stop\|bounce
    fi
)

compress() (
    local started="$( list started | grep ^ )"
    local up="$( list up | grep ^ )"

    cd ~/Library/Containers/com.utmapp.UTM/Data/Documents

    for i in *.utm; do
        # remove .utm from end of dir name
        local candidate="$(echo $i | sed 's/\.utm$//')"
        if grep "$candidate" <( echo $started; echo $up ) >/dev/null 2>/dev/null ; then
            red_text Skipping $i, machine is running
        else
            green_text Compressing $i
            du -sch $i|grep $i|sed 's/^/  before: /'

            for j in $i/Data/*qcow2; do
                qemu-img convert -O qcow2 "$j" shrunk && \
                    mv shrunk "$j"
            done

            du -sch $i|grep $i|sed 's/^/   after: /'
        fi
    done
)

backup () (
    local started="$( list started | grep ^ )"
    local up="$( list up | grep ^ )"

    if [ -z "$started" ] && [ -z "$up" ]; then
        echo Backing up
        cd "/Volumes/VaultBackup/snapshots/daily.0/UTM VMs" && \
        rsync -Pavessh --delete --exclude UTM?storage?dir ~/Library/Containers/com.utmapp.UTM/Data/Documents/ .
    else
        echo Can\'t backup, some machines are still running:
        (
            echo $started
            echo $up
        )|sort|uniq
    fi
)

bounce () (
    _execute_verb_with_arg bounce listup "$@"
)

_do_bounce () (
    MACHINE="$1"
    stop "$MACHINE"
    while grep "^$MACHINE$" <( list started ) >/dev/null 2>&1; do
        sleep 5
        echo ... waiting
    done
    sleep 5
    start "$MACHINE"
)

stop () (
    _execute_verb_with_arg stop listup "$@"
)

_do_stop () (
    MACHINE="$1"
    echo stopping $MACHINE
    utmctl stop "$MACHINE" --request >/dev/null 2>/dev/null
    sleep 5
)

start () (
    _execute_verb_with_arg start liststopped "$@"
)

_do_start () (
    MACHINE="$1"
    echo starting $MACHINE
    utmctl start $MACHINE >/dev/null 2>/dev/null
    while ! _pingvm "$MACHINE"; do
        echo ... waiting
        sleep 5
    done
)

_execute_verb_with_arg () (
    ORIGINAL_VERB="$1"
    shift
    LIST_FUNCTION="$1"
    shift

    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( "$LIST_FUNCTION" ); do
            "$ORIGINAL_VERB" "$candidate"
        done
    elif [ -z "$MACHINE" ]; then
        echo utm "$ORIGINAL_VERB" all\|\{list of machines\}
    elif [ ! -z "$1" ]; then                         # multi? iterate
        for candidate in "$MACHINE" "$@"; do
            "$ORIGINAL_VERB" "$candidate"
        done
    elif [[ "$MACHINE" == *\** ]]; then
        for candidate in $( "$LIST_FUNCTION" ); do
            if [[ "$candidate" == $MACHINE ]]; then
                "$ORIGINAL_VERB" "$candidate"
            fi
        done
    elif grep "^$MACHINE\$" <( "$LIST_FUNCTION" ) >/dev/null 2>/dev/null ; then
        "_do_$ORIGINAL_VERB" "$MACHINE"
    else
        echo What\'s $MACHINE?
    fi
)

status () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for status in stopped started up; do
            STATUSES="$(list $status)"
            if [ ! -z "$STATUSES" ]; then
                echo $status
                echo $STATUSES|sed 's/ /\n/g'|sed 's/^/  /'
            fi
        done
    elif [ -z "$1" ]; then
        echo utm status all\|\{list of machines\}
    elif [ ! -z "$1" ]; then
        echo status \$machine not yet implemented, sorry
    elif [[ "$MACHINE" == *\** ]]; then
        echo status \$wildcard not yet implemented, sorry
    fi
)

list_complete() (
    utmctl list |grep -v UUID
)

listall () (
    list_complete |awk '{print $3}'
)

liststarted () (
    list_complete |awk '$2 ~ /started/ { print $3; next }'
)

listup () (
    for candidate in $( liststarted ); do
        _pingvm "$candidate" && echo $candidate
    done
)

_pingvm () (
    VM="$1"
    ALTERNATE_NAME="$(echo "$VM"|sed 's/.local$//')"
    (ping -c1 "$VM" || ping -c1 "$ALTERNATE_NAME" ) >/dev/null 2>&1 && return 0
    return 1
)

liststopped () (
    grep -v -f <( liststarted ) <( listall )
)

list () (
    TYPE="$1"
    shift
    if [ "$TYPE" == "started" ]; then
        liststarted
    elif [ "$TYPE" == "all" ]; then
        listall
    elif [ "$TYPE" == "up" ]; then
        listup
    elif [ "$TYPE" == "stopped" ]; then
        liststopped
    else
        echo utm list all\|started\|up\|stopped
    fi
)

main "$@"
