#!/usr/bin/env bash

eval "$(cat $HOME/bin/lib/stdbashlib)"

main () (
    VERB="$1"
    shift

    if [ "$VERB" == "list" ]; then
        list "$@"
    elif [ "$VERB" == "start" ]; then
        start "$@"
    elif [ "$VERB" == "stop" ]; then
        stop "$@"
    elif [ "$VERB" == "status" ]; then
        status "$@"
    elif [ "$VERB" == "bounce" ]; then
        bounce "$@"
    elif [ "$VERB" == "compress" ]; then
        compress "$@"
    elif [ "$VERB" == "backup" ]; then
        backup "$@"
    else
        echo vbox list\|start\|stop\|bounce
    fi
)

compress() (
    local started="$( list started | grep ^ )"
    local up="$( list up | grep ^ )"

    cd "$HOME/VirtualBox VMs"

    for i in *; do
        if grep "$i" <( echo $started; echo $up ) >/dev/null 2>/dev/null ; then
            red_text Skipping $i, machine is running
        else
            green_text Compressing $i
            du -sch "$i"|grep "$i"|sed 's/^/  before: /'

            for j in "$i"/*.vdi; do
                VBoxManage modifymedium "$j" --compact 2>/dev/null || red_text It\'s all gone wrong
            done

            du -sch "$i"|grep "$i"|sed 's/^/   after: /'
        fi
    done
)

backup () (
    local started="$( list started | grep ^ )"
    local up="$( list up | grep ^ )"

    if [ -z "$started" ] && [ -z "$up" ]; then
        echo Backing up
        cd "/Volumes/VaultBackup/snapshots/daily.0/VirtualBox VMs" && \
        rsync -Pavessh --delete ~/VirtualBox?VMs/ .
    else
        echo Can\'t backup, some machines are still running:
        (
            echo $started
            echo $up
        )|sort|uniq
    fi
)

bounce () (
    _execute_verb_with_arg bounce listup "$@"
)

_do_bounce () (
    MACHINE="$1"
    stop "$MACHINE"
    while grep "^$MACHINE$" <( list started ) >/dev/null 2>&1; do
        sleep 5
        echo ... waiting
    done
    sleep 5
    start "$MACHINE"
)

stop () (
    _execute_verb_with_arg stop listup "$@"
)

_do_stop () (
    MACHINE="$1"
    echo stopping $MACHINE
    VBoxManage controlvm "$MACHINE" acpipowerbutton >/dev/null 2>/dev/null
)

start () (
    _execute_verb_with_arg start liststopped "$@"
)

_do_start () (
    MACHINE="$1"
    echo starting $MACHINE
    VBoxManage startvm "$MACHINE" >/dev/null 2>/dev/null
)

_execute_verb_with_arg () (
    ORIGINAL_VERB="$1"
    shift
    LIST_FUNCTION="$1"
    shift

    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( "$LIST_FUNCTION" ); do
            "$ORIGINAL_VERB" "$candidate"
        done
    elif [ -z "$MACHINE" ]; then
        echo vbox "$ORIGINAL_VERB" all\|\{list of machines\}
    elif [ ! -z "$1" ]; then
        for candidate in "$MACHINE" "$@"; do
            "$ORIGINAL_VERB" "$candidate"
        done
    elif [[ "$MACHINE" == *\** ]]; then
        for candidate in $( "$LIST_FUNCTION" ); do
            if [[ "$candidate" == $MACHINE ]]; then
                "$ORIGINAL_VERB" "$candidate"
            fi
        done
    elif _is_protected_vm "$MACHINE"; then
        _protected_vm_message "$ORIGINAL_VERB" "$MACHINE"
    elif grep "^$MACHINE\$" <( "$LIST_FUNCTION" ) >/dev/null 2>/dev/null ; then
        "_do_$ORIGINAL_VERB" "$MACHINE"
    else
        echo What\'s $MACHINE?
    fi
)

_is_protected_vm () (
    [ "$1" == "GCA-XP" ]
)

_protected_vm_message () (
    VERB="$1"
    MACHINE="$2"

    case "$VERB" in
        bounce) echo no, not bouncing $MACHINE ;;
        start) echo no, not starting $MACHINE ;;
        stop) echo no, not stopping $MACHINE ;;
    esac
)

status () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for status in stopped started up; do
            STATUSES="$(list $status)"
            if [ ! -z "$STATUSES" ]; then
                echo $status
                echo $STATUSES|sed 's/ /\n/g'|sed 's/^/  /'
            fi
        done
    elif [ -z "$1" ]; then
        echo vbox status all\|\{list of machines\}
    elif [ ! -z "$1" ]; then
        echo status \$machine not yet implemented, sorry
    elif [[ "$MACHINE" == *\** ]]; then
        echo status \$wildcard not yet implemented, sorry
    fi
)

listall () (
    VBoxManage list vms |awk '{print $1}'|sed 's/"//'g
)

liststarted () (
    VBoxManage list runningvms |awk '{print $1}'|sed 's/"//'g
)

listup () (
    for candidate in $( liststarted ); do
        ping -c1 "$candidate" >/dev/null 2>/dev/null && echo $candidate
    done
)

liststopped () (
    grep -v -f <( liststarted ) <( listall )
)

list () (
    TYPE="$1"
    shift
    if [ "$TYPE" == "started" ]; then
        liststarted
    elif [ "$TYPE" == "all" ]; then
        listall
    elif [ "$TYPE" == "up" ]; then
        listup
    elif [ "$TYPE" == "stopped" ]; then
        liststopped
    else
        echo vbox list all\|started\|up\|stopped
    fi
)

main "$@"
