#!/usr/bin/env bash

main () (
    VERB="$1"
    shift

    if [ "$VERB" == "list" ]; then
        list "$@"
    elif [ "$VERB" == "start" ]; then
        start "$@"
    elif [ "$VERB" == "stop" ]; then
        stop "$@"
    elif [ "$VERB" == "status" ]; then
        status "$@"
    elif [ "$VERB" == "bounce" ]; then
        bounce "$@"
    else
        echo vbox list\|start\|stop\|bounce
    fi
)

bounce () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( list up ); do
            bounce "$candidate"
        done
    elif [ "$MACHINE" == "GCA-XP" ]; then
        echo no, not bouncing $MACHINE
    elif [ -z "$MACHINE" ]; then                        # no args? error
        echo vbox bounce all\|\{list of machines\}
    elif [ ! -z "$1" ]; then                            # multi? iterate
        for candidate in "$MACHINE" "$@"; do
            bounce "$candidate"
        done
    elif [[ "$MACHINE" == *\** ]]; then                 # wildcard? match and iterate
        for candidate in $( list up ); do
            if [[ "$candidate" == $MACHINE ]]; then
                bounce "$candidate"
            fi
        done
    else
        if grep ^$MACHINE\$ <( list up ) >/dev/null 2>/dev/null ; then
            stop "$MACHINE"
            while grep "^$MACHINE$" <( list started ) >/dev/null 2>&1; do
                sleep 5
                echo ... waiting
            done
            sleep 5
            start "$MACHINE"
        else
            echo What\'s $MACHINE?
        fi
    fi
)

stop () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( list up ); do
            stop "$candidate"
        done
    elif [ "$MACHINE" == "GCA-XP" ]; then
        echo no, not stopping $MACHINE
    elif [ -z "$MACHINE" ]; then
        echo vbox stop all\|\{list of machines\}
    elif [ ! -z "$1" ]; then
        for candidate in "$MACHINE" "$@"; do
            stop "$candidate"
        done
    elif [[ "$MACHINE" == *\** ]]; then
        for candidate in $( list up ); do
            if [[ "$candidate" == $MACHINE ]]; then
                stop "$candidate"
            fi
        done
    else
        if grep ^$MACHINE\$ <( list up ) >/dev/null 2>/dev/null ; then
            echo stopping $MACHINE
            VBoxManage controlvm "$MACHINE" acpipowerbutton >/dev/null 2>/dev/null
        else
            echo What\'s $MACHINE?
        fi
    fi
)

start () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for candidate in  $( list stopped ); do
            start "$candidate"
        done
    elif [ "$MACHINE" == "GCA-XP" ]; then
        echo no, not starting $MACHINE
    elif [ -z "$MACHINE" ]; then
        echo vbox start all\|\{list of machines\}
    elif [ ! -z "$1" ]; then
        for candidate in "$MACHINE" "$@"; do
            start "$candidate"
        done
    elif [[ "$MACHINE" == *\** ]]; then
        for candidate in $( list stopped ); do
            if [[ "$candidate" == $MACHINE ]]; then
                start "$candidate"
            fi
        done
    else
        if grep ^$MACHINE\$ <( list stopped ) >/dev/null 2>/dev/null ; then
            echo starting $MACHINE
            VBoxManage startvm $MACHINE >/dev/null 2>/dev/null
        else
            echo What\'s $MACHINE?
        fi
    fi
)

status () (
    MACHINE="$1"
    shift
    if [ "$MACHINE" == "all" ]; then
        for status in stopped started up; do
            STATUSES="$(list $status)"
            if [ ! -z "$STATUSES" ]; then
                echo $status
                echo $STATUSES|sed 's/ /\n/g'|sed 's/^/  /'
            fi
        done
    elif [ -z "$1" ]; then
        echo vbox status all\|\{list of machines\}
    elif [ ! -z "$1" ]; then
        echo status \$machine not yet implemented, sorry
    elif [[ "$MACHINE" == *\** ]]; then
        echo status \$wildcard not yet implemented, sorry
    fi
)

listall () (
    VBoxManage list vms |awk '{print $1}'|sed 's/"//'g
)

liststarted () (
    VBoxManage list runningvms |awk '{print $1}'|sed 's/"//'g
)

listup () (
    for candidate in $( liststarted ); do
        ping -c1 $candidate >/dev/null 2>/dev/null && echo $candidate
    done
)

list () (
    TYPE="$1"
    shift
    if [ "$TYPE" == "started" ]; then
        liststarted
    elif [ "$TYPE" == "all" ]; then
        listall
    elif [ "$TYPE" == "up" ]; then
        listup
    elif [ "$TYPE" == "stopped" ]; then
        grep -v -f <( liststarted ) <( listall )
    else
        echo vbox list all\|started\|up\|stopped
    fi
)

main "$@"
