#!/usr/bin/env bash

MACHINE="$1"

[ -z "$MACHINE" ] || (
    VBoxManage controlvm "$MACHINE" acpipowerbutton
    while VBoxManage list runningvms|grep -q "$MACHINE"; do
        echo still running
        sleep 10
    done
    echo stopped

    VBoxManage startvm $MACHINE
    while ! ping -c1 $MACHINE.local >/dev/null 2>&1; do
        echo not yet up
    done
    echo Running
)

