#!/usr/bin/env bash

# This contains a bunch of useful functions for use in scripts. For Reasons,
# it should be pulled into your script not using `source` but thus:
#
#   eval "$(cat $HOME/bin/lib/stdbashlib)"

no_colour='\e[0m'

function black_on_red_text {
    echo -e '\e[0;30;41m'"$@"$no_colour
}
function black_on_orange_text {
    echo -e '\e[0;30;48;5;208m'"$@"$no_colour
}
function black_on_yellow_text {
    echo -e '\e[0;30;43m'"$@"$no_colour
}
function black_on_green_text {
    echo -e '\e[0;30;42m'"$@"$no_colour
}
function black_on_blue_text {
    echo -e '\e[0;30;44m'"$@"$no_colour
}
function black_on_purple_text {
    echo -e '\e[0;30;45m'"$@"$no_colour
}
function black_on_white_text {
    echo -e '\e[0;30;47m'"$@"$no_colour
}

function red_text {
    echo -e '\e[1;31m'"$@"$no_colour
}
function orange_text {
    echo -e '\e[38;5;208m'"$@"$no_colour
}
function yellow_text {
    echo -e '\e[0;33m'"$@"$no_colour
}
function green_text {
    echo -e '\e[1;32m'"$@"$no_colour
}
function blue_text {
    echo -e '\e[1;34m'"$@"$no_colour
}
function purple_text {
    echo -e '\e[1;35m'"$@"$no_colour
}
function white_text {
    echo -e '\e[1;37m'"$@"$no_colour
}

function script_dir (
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")" > /dev/null 2>&1
    pwd
)

function start_timer {
    timer_start_time=$(date +%s)
}

function end_timer {
    timer_elapsed_seconds=$(( $(date +%s) - timer_start_time ))
    unset timer_start_time
}

function timer_elapsed_seconds {
    echo $timer_elapsed_seconds
    unset timer_elapsed_seconds
}

STDLIB_ORIG_PATH="$PATH"

function remove_from_path {
    local dir=$1
    PATH=:$PATH:
    PATH=${PATH//:$dir:/:}
    PATH=${PATH#:}
    export PATH=${PATH%:}
}

function restore_original_path {
    export PATH="$STDLIB_ORIG_PATH"
}
