#!/usr/bin/env bash

# This contains a bunch of useful functions for use in scripts. For Reasons,
# it should be pulled into your script not using `source` but thus:
#
#   eval "$(cat $HOME/bin/lib/stdbashlib)"

function script_dir (
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")" > /dev/null 2>&1
    pwd
)

function seconds-to-hms {
    local format=$1
    local total_seconds=$2

    local hours=$(( total_seconds / 3600 ))
    local minutes=$(( (total_seconds % 3600) / 60 ))
    local seconds=$(( total_seconds % 60 ))
    printf "$format\n" $hours $minutes $seconds
}

function start_timer {
    timer_start_time=$(date +%s)
}

function end_timer {
    timer_elapsed_seconds=$(( $(date +%s) - timer_start_time ))
    unset timer_start_time
}

function timer_elapsed_seconds {
    echo $timer_elapsed_seconds
    unset timer_elapsed_seconds
}

STDLIB_ORIG_PATH="$PATH"

function remove_from_path {
    local dir=$1
    PATH=:$PATH:
    PATH=${PATH//:$dir:/:}
    PATH=${PATH#:}
    export PATH=${PATH%:}
}

function restore_original_path {
    export PATH="$STDLIB_ORIG_PATH"
}
